name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Create artifact
        run: |
          mkdir -p dist

          cat > dist/hello.txt <<EOF
          Hello from emacs-linux CI!
          Built on:
          $(date -u)
          Architecture:
          $(uname -m)
          EOF

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-linux
          path: dist/hello.txt
